// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
package rest

import (
	"encoding/json"
	"net/http"

	"veriqo/veriqo/registry"
)

// Routes returns the generated HTTP route table: "/{engine}/{method}"
// (POST, JSON body) -> handler, mechanically derived from
// veriqo/contracts/*.yaml.
func Routes(reg *registry.Registry) map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
		"/evidence/add_node":               handleEvidenceAddNode(reg),
		"/evidence/add_edge":               handleEvidenceAddEdge(reg),
		"/evidence/lineage":                handleEvidenceLineage(reg),
		"/evidence/influenced":             handleEvidenceInfluenced(reg),
		"/evidence/stats":                  handleEvidenceStats(reg),
		"/intent/verify":                   handleIntentVerify(reg),
		"/intent/certify":                  handleIntentCertify(reg),
		"/intent/ledger":                   handleIntentLedger(reg),
		"/policy/evaluate":                 handlePolicyEvaluate(reg),
		"/policy/ledger":                   handlePolicyLedger(reg),
		"/policy/verify_chain":             handlePolicyVerifyChain(reg),
		"/reasoning/assert":                handleReasoningAssert(reg),
		"/reasoning/infer":                 handleReasoningInfer(reg),
		"/reasoning/query":                 handleReasoningQuery(reg),
		"/reasoning/explain":               handleReasoningExplain(reg),
		"/replay/contradiction":            handleReplayContradiction(reg),
		"/replay/fusion":                   handleReplayFusion(reg),
		"/trust/evaluate":                  handleTrustEvaluate(reg),
		"/trust/certify":                   handleTrustCertify(reg),
		"/trust/ledger":                    handleTrustLedger(reg),
		"/trust/verify_ledger":             handleTrustVerifyLedger(reg),
		"/verification/verify":             handleVerificationVerify(reg),
		"/verification/verify_certificate": handleVerificationVerifyCertificate(reg),
	}
}

type reqEvidenceAddNode struct {
	Kind    string "json:\"kind\""
	Payload string "json:\"payload\""
}

// Register (or dedupe onto) a content-addressed evidence node and return its NodeID.
func handleEvidenceAddNode(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqEvidenceAddNode
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Evidence.AddNode(req.Kind, req.Payload)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqEvidenceAddEdge struct {
	From     string "json:\"from\""
	To       string "json:\"to\""
	Relation string "json:\"relation\""
}

// Record a provenance relationship between two existing nodes (relation: derived_from|supports|contradicts|corrects).
func handleEvidenceAddEdge(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqEvidenceAddEdge
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Evidence.AddEdge(req.From, req.To, req.Relation)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqEvidenceLineage struct {
	Id string "json:\"id\""
}

// Return the full ancestry of a node — everything it was derived from or corrected by, breadth-first.
func handleEvidenceLineage(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqEvidenceLineage
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Evidence.Lineage(req.Id)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqEvidenceInfluenced struct {
	Id string "json:\"id\""
}

// Return everything a node influenced forward — the exact inverse traversal of lineage.
func handleEvidenceInfluenced(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqEvidenceInfluenced
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Evidence.Influenced(req.Id)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqEvidenceStats struct {
}

// Return the current node/edge counts.
func handleEvidenceStats(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqEvidenceStats
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Evidence.Stats()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqIntentVerify struct {
	IntentId       string  "json:\"intent_id\""
	Subject        string  "json:\"subject\""
	ExpectedAction string  "json:\"expected_action\""
	ObservedAction string  "json:\"observed_action\""
	ExpectedRisk   float64 "json:\"expected_risk\""
	ObservedRisk   float64 "json:\"observed_risk\""
	Tick           uint64  "json:\"tick\""
}

// Compare a declared intent's expected outcome to what was actually observed and compute the trust delta, without issuing a certificate.
func handleIntentVerify(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqIntentVerify
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Intent.Verify(req.IntentId, req.Subject, req.ExpectedAction, req.ObservedAction, req.ExpectedRisk, req.ObservedRisk, req.Tick)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqIntentCertify struct {
	IntentId       string  "json:\"intent_id\""
	Subject        string  "json:\"subject\""
	ExpectedAction string  "json:\"expected_action\""
	ObservedAction string  "json:\"observed_action\""
	ExpectedRisk   float64 "json:\"expected_risk\""
	ObservedRisk   float64 "json:\"observed_risk\""
	Tick           uint64  "json:\"tick\""
}

// Verify, and issue a hash-chained trust certificate if the subject's running accuracy clears its policy threshold.
func handleIntentCertify(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqIntentCertify
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Intent.Certify(req.IntentId, req.Subject, req.ExpectedAction, req.ObservedAction, req.ExpectedRisk, req.ObservedRisk, req.Tick)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqIntentLedger struct {
}

// Return the full hash-chained trust certificate history for this Verifier.
func handleIntentLedger(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqIntentLedger
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Intent.Ledger()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqPolicyEvaluate struct {
	Action        string  "json:\"action\""
	Subject       string  "json:\"subject\""
	RiskAction    string  "json:\"risk_action\""
	TrustScore    float64 "json:\"trust_score\""
	OntologyValid string  "json:\"ontology_valid\""
}

// Gate one action; ontology_valid is \"true\"/\"false\". Returns ALLOW, DENY, or REQUIRE_APPROVAL.
func handlePolicyEvaluate(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqPolicyEvaluate
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Policy.Evaluate(req.Action, req.Subject, req.RiskAction, req.TrustScore, req.OntologyValid)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqPolicyLedger struct {
}

// Return the full hash-chained gating decision log.
func handlePolicyLedger(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqPolicyLedger
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Policy.Ledger()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqPolicyVerifyChain struct {
}

// Re-derive every logged decision's hash and confirm chain linkage (tamper detection).
func handlePolicyVerifyChain(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqPolicyVerifyChain
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Policy.VerifyChain()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqReasoningAssert struct {
	Subject   string "json:\"subject\""
	Predicate string "json:\"predicate\""
	Object    string "json:\"object\""
}

// Assert one ground fact (subject, predicate, object) into the knowledge base.
func handleReasoningAssert(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqReasoningAssert
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Reasoning.Assert(req.Subject, req.Predicate, req.Object)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqReasoningInfer struct {
}

// Run forward-chaining inference to a fixpoint against the built-in rule set; returns the number of newly derived facts.
func handleReasoningInfer(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqReasoningInfer
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Reasoning.Infer()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqReasoningQuery struct {
	Subject   string "json:\"subject\""
	Predicate string "json:\"predicate\""
	Object    string "json:\"object\""
}

// Query facts matching a pattern; use a leading '?' on subject/predicate/object to match any value (e.g. '?x').
func handleReasoningQuery(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqReasoningQuery
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Reasoning.Query(req.Subject, req.Predicate, req.Object)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqReasoningExplain struct {
	Subject   string "json:\"subject\""
	Predicate string "json:\"predicate\""
	Object    string "json:\"object\""
}

// Return the derivation trace (which rule fired, over which premises) for a derived fact.
func handleReasoningExplain(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqReasoningExplain
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Reasoning.Explain(req.Subject, req.Predicate, req.Object)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqReplayContradiction struct {
	Subject     string "json:\"subject\""
	RecordsJson string "json:\"records_json\""
}

// Independently recompute a contradiction-arbitration claim from raw evidence records (JSON array, must include one contradiction.ArbitrationParams record).
func handleReplayContradiction(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqReplayContradiction
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Replay.Contradiction(req.Subject, req.RecordsJson)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqReplayFusion struct {
	Subject     string "json:\"subject\""
	RecordsJson string "json:\"records_json\""
}

// Independently recompute a fusion-arbitration result from raw evidence records (JSON array, must include one fusion arbitration-params record).
func handleReplayFusion(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqReplayFusion
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Replay.Fusion(req.Subject, req.RecordsJson)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqTrustEvaluate struct {
	SubjectId         string  "json:\"subject_id\""
	WinRate           float64 "json:\"win_rate\""
	ContradictionRate float64 "json:\"contradiction_rate\""
	Tick              uint64  "json:\"tick\""
}

// Compute a trust score for a subject from win_rate/contradiction_rate evidence, without issuing a certificate.
func handleTrustEvaluate(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqTrustEvaluate
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Trust.Evaluate(req.SubjectId, req.WinRate, req.ContradictionRate, req.Tick)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqTrustCertify struct {
	SubjectId         string  "json:\"subject_id\""
	WinRate           float64 "json:\"win_rate\""
	ContradictionRate float64 "json:\"contradiction_rate\""
	Tick              uint64  "json:\"tick\""
}

// Evaluate, and issue a hash-chained TrustCertificate if the score clears the policy threshold.
func handleTrustCertify(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqTrustCertify
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Trust.Certify(req.SubjectId, req.WinRate, req.ContradictionRate, req.Tick)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqTrustLedger struct {
}

// Return the full hash-chained certificate history.
func handleTrustLedger(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqTrustLedger
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Trust.Ledger()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqTrustVerifyLedger struct {
}

// Re-derive every certificate's hash and confirm chain linkage (tamper detection).
func handleTrustVerifyLedger(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqTrustVerifyLedger
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Trust.VerifyLedger()
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqVerificationVerify struct {
	Domain        string "json:\"domain\""
	Subject       string "json:\"subject\""
	RecordsJson   string "json:\"records_json\""
	ClaimedResult string "json:\"claimed_result\""
}

// records_json is a JSON array of {\"Kind\":..,\"Index\":..,\"Payload\":<base64>}; domain selects the independent replay function (\"contradiction\" or \"fusion\").
func handleVerificationVerify(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqVerificationVerify
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Verification.Verify(req.Domain, req.Subject, req.RecordsJson, req.ClaimedResult)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}

type reqVerificationVerifyCertificate struct {
	CertificateJson string "json:\"certificate_json\""
}

// Given a previously-issued AuditCertificate as JSON, confirm (third-party, bundle-free) that it has not been altered.
func handleVerificationVerifyCertificate(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req reqVerificationVerifyCertificate
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.Verification.VerifyCertificate(req.CertificateJson)
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			_ = reg.SaveState()
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result)
	}
}
