package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

const cliTemplate = `// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"veriqo/veriqo/registry"
)

// commandTable maps "engine method" to its handler, built from the
// contract files at generation time — the CLI never hand-maintains
// this list.
var commandTable = map[string]func(reg *registry.Registry, args []string) error{
{{- range $c := .Contracts }}
{{- range $m := $c.Methods }}
	"{{ $c.Engine }} {{ $m.Name }}": cmd{{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }},
{{- end }}
{{- end }}
}

{{ range $c := .Contracts }}
{{ range $m := $c.Methods }}
// {{ $m.Description }}
func cmd{{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }}(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("{{ $c.Engine }} {{ $m.Name }}", flag.ExitOnError)
{{- range $p := $m.Params }}
	{{ $p.Name }} := fs.{{ FlagFunc $p.Type }}("{{ $p.Name }}", {{ ZeroValue $p.Type }}, "{{ $p.Name }} ({{ $p.Type }})")
{{- end }}
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.{{ GoEngineName $c.Engine }}.{{ GoMethodName $m.Name }}({{ ParamRefs $m.Params }})
	if err != nil {
		return fmt.Errorf("{{ $c.Engine }} {{ $m.Name }}: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}
{{ end }}
{{ end }}
`

const sdkTemplate = `// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
//
// Client is the generated Go SDK: a typed wrapper per contract method.
// This session's honest scope: the SDK calls the Engine Registry
// in-process (Go function calls) rather than over a network transport
// — Contract -> Serialize -> Transport -> Return with a real
// network/gRPC transport is the explicitly-named next step, not
// fabricated here. What IS real: every method below is generated
// mechanically from the same contract the CLI is generated from, and
// calls straight through to the same tested registry.Registry used by
// the CLI and gateway, so all three surfaces are provably consistent
// with each other by construction.
package sdk

import (
	"veriqo/pkg/evidence/graph"
	"veriqo/pkg/kernel/intent"
	"veriqo/pkg/kernel/policy"
	"veriqo/pkg/kernel/reasoning"
	"veriqo/pkg/trust"
	"veriqo/veriqo/registry"
)

// Client wraps a Registry with typed, contract-generated methods.
type Client struct {
	reg *registry.Registry
}

// NewClient builds an SDK client around a real Registry (which in turn
// wraps the real, tested pkg/trust and pkg/kernel/intent engines).
func NewClient(reg *registry.Registry) *Client { return &Client{reg: reg} }
{{ range $c := .Contracts }}
{{ range $m := $c.Methods }}
// {{ $m.Description }}
func (c *Client) {{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }}({{ ParamDecls $m.Params }}) ({{ GoReturnType $m.Returns }}, error) {
	return c.reg.{{ GoEngineName $c.Engine }}.{{ GoMethodName $m.Name }}({{ ParamRefsNoDeref $m.Params }})
}
{{ end }}
{{ end }}
`

// restTemplate renders the generated REST gateway route table: one
// POST /{engine}/{method} handler per contract method, decoding a flat
// JSON body into the same primitive params the CLI/SDK use and
// dispatching through the identical registry.Registry — so the
// gateway is provably consistent with the CLI/SDK by construction,
// exactly like the CLI/SDK pair already were.
const restTemplate = `// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
package rest

import (
	"encoding/json"
	"net/http"

	"veriqo/veriqo/registry"
)

// Routes returns the generated HTTP route table: "/{engine}/{method}"
// (POST, JSON body) -> handler, mechanically derived from
// veriqo/contracts/*.yaml.
func Routes(reg *registry.Registry) map[string]http.HandlerFunc {
	return map[string]http.HandlerFunc{
{{- range $c := .Contracts }}
{{- range $m := $c.Methods }}
		"/{{ $c.Engine }}/{{ $m.Name }}": handle{{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }}(reg),
{{- end }}
{{- end }}
	}
}
{{ range $c := .Contracts }}
{{ range $m := $c.Methods }}
type req{{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }} struct {
{{- range $p := $m.Params }}
	{{ GoFieldName $p.Name }} {{ $p.GoType }} "json:\"{{ $p.Name }}\""
{{- end }}
}

// {{ $m.Description }}
func handle{{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }}(reg *registry.Registry) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
			return
		}
		var req req{{ GoEngineName $c.Engine }}{{ GoMethodName $m.Name }}
		if r.Body != nil {
			defer r.Body.Close()
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				http.Error(w, "invalid JSON body: "+err.Error(), http.StatusBadRequest)
				return
			}
		}
		result, err := reg.{{ GoEngineName $c.Engine }}.{{ GoMethodName $m.Name }}({{ ReqFieldRefs $m.Params }})
		if err != nil {
			http.Error(w, err.Error(), http.StatusUnprocessableEntity)
			return
		}
		if reg.HasPersistence() {
			// A silently-dropped SaveState failure would return 200 OK
			// with a correct in-memory result while the state change
			// itself was never durably persisted -- invisible data loss
			// on the next restart. Surfaced as 500 so the caller knows
			// this specific write is not safely durable, rather than a
			// false-green 200.
			if err := reg.SaveState(); err != nil {
				http.Error(w, "state persistence failed: "+err.Error(), http.StatusInternalServerError)
				return
			}
		}
		w.Header().Set("Content-Type", "application/json")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		_ = enc.Encode(result) // response body write failure (e.g. client disconnected mid-write) cannot be meaningfully surfaced: headers are already sent by this point
	}
}
{{ end }}
{{ end }}
`

// pythonTemplate renders a dependency-free (stdlib urllib only) Python
// SDK: one method per contract method, calling the same REST gateway
// generated above. Honest scope: unlike the typed Go SDK, this client
// is untyped over JSON (Python's stdlib gives no code-generation-
// friendly typed-client story without a third-party dependency, which
// this repo's zero-external-dependency discipline rules out) — it is
// still generated mechanically from the same contracts, not hand-
// written, and calls straight through to the real gateway/registry.
const pythonTemplate = `# Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
# Regenerate with: go run ./veriqo/generator/cmd/gen
#
# VeriqoClient is the generated Python SDK: a thin, stdlib-only HTTP
# client per contract method, calling the veriqo/gateway/rest gateway
# that fronts the same Engine Registry the Go CLI and Go SDK call —
# every surface derives from one contract and cannot silently drift.
import json
import urllib.request
import urllib.error


class VeriqoError(Exception):
    pass


class VeriqoClient:
    def __init__(self, base_url="http://127.0.0.1:8080"):
        self.base_url = base_url.rstrip("/")

    def _post(self, path, payload):
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self.base_url + path,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            raise VeriqoError("%s %s failed: %s %s" % (req.method, path, e.code, e.read().decode("utf-8", "replace")))
{{ range $c := .Contracts }}
{{ range $m := $c.Methods }}
    def {{ $c.Engine }}_{{ $m.Name }}(self{{ PyParamDecls $m.Params }}):
        """{{ $m.Description }}"""
        return self._post("/{{ $c.Engine }}/{{ $m.Name }}", {
{{- range $p := $m.Params }}
            "{{ $p.Name }}": {{ PySafeName $p.Name }},
{{- end }}
        })
{{ end }}
{{ end }}
`

// typescriptTemplate renders a dependency-free (fetch only) TypeScript
// SDK, same honest-scope note as the Python client above: untyped over
// JSON (any), generated mechanically, calling the same REST gateway.
const typescriptTemplate = `// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
//
// VeriqoClient is the generated TypeScript SDK: a thin, dependency-
// free (fetch only) HTTP client per contract method, calling the
// veriqo/gateway/rest gateway that fronts the same Engine Registry the
// Go CLI/SDK and Python SDK call.

export class VeriqoError extends Error {}

export class VeriqoClient {
  private baseUrl: string;

  constructor(baseUrl: string = "http://127.0.0.1:8080") {
    this.baseUrl = baseUrl.replace(/\/$/, "");
  }

  private async post(path: string, payload: unknown): Promise<any> {
    const res = await fetch(this.baseUrl + path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const body = await res.text();
      throw new VeriqoError("POST " + path + " failed: " + res.status + " " + body);
    }
    return res.json();
  }
{{ range $c := .Contracts }}
{{ range $m := $c.Methods }}
  /** {{ $m.Description }} */
  async {{ TsMethodName $c.Engine $m.Name }}({{ TsParamDecls $m.Params }}): Promise<any> {
    return this.post("/{{ $c.Engine }}/{{ $m.Name }}", { {{ TsObjLiteral $m.Params }} });
  }
{{ end }}
{{ end }}
}
`

// pythonKeywords is every contract param name this repo's contracts
// currently use that collides with a Python reserved word. pySafeName
// suffixes a trailing underscore for these — the conventional Python
// idiom (e.g. "from_") — so the generated parameter is valid Python
// while the JSON wire field name (what the server actually reads)
// stays exactly as the contract declares it.
var pythonKeywords = map[string]bool{
	"from": true, "import": true, "class": true, "is": true, "in": true,
	"for": true, "if": true, "else": true, "def": true, "return": true,
	"global": true, "lambda": true, "not": true, "or": true, "and": true,
	"pass": true, "with": true, "as": true, "type": true,
}

func pySafeName(name string) string {
	if pythonKeywords[name] {
		return name + "_"
	}
	return name
}

var funcMap = template.FuncMap{
	"GoEngineName": GoEngineName,
	"GoMethodName": GoMethodName,
	"FlagFunc": func(t string) string {
		switch t {
		case "float":
			return "Float64"
		case "uint":
			return "Uint64"
		default:
			return "String"
		}
	},
	"ZeroValue": func(t string) string {
		switch t {
		case "float":
			return "0"
		case "uint":
			return "0"
		default:
			return `""`
		}
	},
	"ParamRefs": func(params []Param) string {
		refs := make([]string, len(params))
		for i, p := range params {
			refs[i] = "*" + p.Name
		}
		return strings.Join(refs, ", ")
	},
	"ParamRefsNoDeref": func(params []Param) string {
		names := make([]string, len(params))
		for i, p := range params {
			names[i] = p.Name
		}
		return strings.Join(names, ", ")
	},
	"ParamDecls": func(params []Param) string {
		decls := make([]string, len(params))
		for i, p := range params {
			decls[i] = p.Name + " " + p.GoType()
		}
		return strings.Join(decls, ", ")
	},
	"GoFieldName": GoMethodName, // same snake_case -> CamelCase transform, reused for JSON struct field names
	"ReqFieldRefs": func(params []Param) string {
		refs := make([]string, len(params))
		for i, p := range params {
			refs[i] = "req." + GoMethodName(p.Name)
		}
		return strings.Join(refs, ", ")
	},
	"PyParamDecls": func(params []Param) string {
		var b strings.Builder
		for _, p := range params {
			b.WriteString(", ")
			b.WriteString(pySafeName(p.Name))
		}
		return b.String()
	},
	"PySafeName": pySafeName,
	"TsMethodName": func(engineName, methodName string) string {
		// lowerCamel(engine) + PascalCase(method), e.g. "trust"+"Evaluate" -> "trustEvaluate"
		return engineName + GoMethodName(methodName)
	},
	"TsParamDecls": func(params []Param) string {
		decls := make([]string, len(params))
		for i, p := range params {
			tsType := "string"
			if p.Type == "float" || p.Type == "uint" {
				tsType = "number"
			}
			decls[i] = p.Name + ": " + tsType
		}
		return strings.Join(decls, ", ")
	},
	"TsObjLiteral": func(params []Param) string {
		names := make([]string, len(params))
		for i, p := range params {
			names[i] = p.Name
		}
		return strings.Join(names, ", ")
	},
	// GoReturnType maps a contract's declared return type to the real Go
	// type the registry method actually returns. This mapping is
	// necessarily hand-maintained (it bridges the contract's abstract
	// return-type name to a concrete Go package type) rather than
	// derived, and is the one place a new contract method with a new
	// return shape requires a one-line addition here.
	"GoReturnType": func(t string) string {
		switch t {
		case "TrustScore":
			return "trust.TrustScore"
		case "TrustCertificateList":
			return "[]trust.TrustCertificate"
		case "Verdict":
			return "intent.Verdict"
		case "NodeList":
			return "[]graph.Node"
		case "TripleList":
			return "[]reasoning.Triple"
		case "Derivation":
			return "reasoning.Derivation"
		case "PolicyLedger":
			return "[]policy.Record"
		case "uint":
			return "uint64"
		case "string":
			return "string"
		default:
			return "any"
		}
	},
}

// GenerateCLI renders the CLI dispatch source for the given contracts,
// gofmt-formatted.
func GenerateCLI(contracts []Contract) ([]byte, error) {
	return renderGo("cli", cliTemplate, contracts)
}

// GenerateSDK renders the Go SDK client source for the given
// contracts, gofmt-formatted.
func GenerateSDK(contracts []Contract) ([]byte, error) {
	return renderGo("sdk", sdkTemplate, contracts)
}

// GenerateREST renders the REST gateway route table for the given
// contracts, gofmt-formatted.
func GenerateREST(contracts []Contract) ([]byte, error) {
	return renderGo("rest", restTemplate, contracts)
}

// renderGo is render plus a go/format.Source pass — every Go artifact
// this generator emits (CLI, Go SDK, REST gateway) is formatted before
// being written, so `gofmt -l` on the committed output is always clean
// regardless of the template's own whitespace.
func renderGo(name, tpl string, contracts []Contract) ([]byte, error) {
	src, err := render(name, tpl, contracts)
	if err != nil {
		return nil, err
	}
	formatted, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("generator: gofmt-formatting %s output: %w", name, err)
	}
	return formatted, nil
}

// GeneratePython renders the Python SDK client for the given
// contracts. Unlike GenerateCLI/GenerateSDK/GenerateREST, this is not
// Go source, so the caller must not run it through gofmt.
func GeneratePython(contracts []Contract) ([]byte, error) {
	return render("python", pythonTemplate, contracts)
}

// GenerateTypeScript renders the TypeScript SDK client for the given
// contracts. Not Go source — do not gofmt the result.
func GenerateTypeScript(contracts []Contract) ([]byte, error) {
	return render("typescript", typescriptTemplate, contracts)
}

func render(name, tpl string, contracts []Contract) ([]byte, error) {
	t, err := template.New(name).Funcs(funcMap).Parse(tpl)
	if err != nil {
		return nil, fmt.Errorf("generator: parsing %s template: %w", name, err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, struct{ Contracts []Contract }{contracts}); err != nil {
		return nil, fmt.Errorf("generator: executing %s template: %w", name, err)
	}
	return buf.Bytes(), nil
}
