# Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
# Regenerate with: go run ./veriqo/generator/cmd/gen
#
# VeriqoClient is the generated Python SDK: a thin, stdlib-only HTTP
# client per contract method, calling the veriqo/gateway/rest gateway
# that fronts the same Engine Registry the Go CLI and Go SDK call —
# every surface derives from one contract and cannot silently drift.
import json
import urllib.request
import urllib.error


class VeriqoError(Exception):
    pass


class VeriqoClient:
    def __init__(self, base_url="http://127.0.0.1:8080"):
        self.base_url = base_url.rstrip("/")

    def _post(self, path, payload):
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self.base_url + path,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        try:
            with urllib.request.urlopen(req) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            raise VeriqoError("%s %s failed: %s %s" % (req.method, path, e.code, e.read().decode("utf-8", "replace")))


    def evidence_add_node(self, kind, payload):
        """Register (or dedupe onto) a content-addressed evidence node and return its NodeID."""
        return self._post("/evidence/add_node", {
            "kind": kind,
            "payload": payload,
        })

    def evidence_add_edge(self, from_, to, relation):
        """Record a provenance relationship between two existing nodes (relation: derived_from|supports|contradicts|corrects)."""
        return self._post("/evidence/add_edge", {
            "from": from_,
            "to": to,
            "relation": relation,
        })

    def evidence_lineage(self, id):
        """Return the full ancestry of a node — everything it was derived from or corrected by, breadth-first."""
        return self._post("/evidence/lineage", {
            "id": id,
        })

    def evidence_influenced(self, id):
        """Return everything a node influenced forward — the exact inverse traversal of lineage."""
        return self._post("/evidence/influenced", {
            "id": id,
        })

    def evidence_stats(self):
        """Return the current node/edge counts."""
        return self._post("/evidence/stats", {
        })



    def intent_verify(self, intent_id, subject, expected_action, observed_action, expected_risk, observed_risk, tick):
        """Compare a declared intent's expected outcome to what was actually observed and compute the trust delta, without issuing a certificate."""
        return self._post("/intent/verify", {
            "intent_id": intent_id,
            "subject": subject,
            "expected_action": expected_action,
            "observed_action": observed_action,
            "expected_risk": expected_risk,
            "observed_risk": observed_risk,
            "tick": tick,
        })

    def intent_certify(self, intent_id, subject, expected_action, observed_action, expected_risk, observed_risk, tick):
        """Verify, and issue a hash-chained trust certificate if the subject's running accuracy clears its policy threshold."""
        return self._post("/intent/certify", {
            "intent_id": intent_id,
            "subject": subject,
            "expected_action": expected_action,
            "observed_action": observed_action,
            "expected_risk": expected_risk,
            "observed_risk": observed_risk,
            "tick": tick,
        })

    def intent_ledger(self):
        """Return the full hash-chained trust certificate history for this Verifier."""
        return self._post("/intent/ledger", {
        })



    def policy_evaluate(self, action, subject, risk_action, trust_score, ontology_valid):
        """Gate one action; ontology_valid is \"true\"/\"false\". Returns ALLOW, DENY, or REQUIRE_APPROVAL."""
        return self._post("/policy/evaluate", {
            "action": action,
            "subject": subject,
            "risk_action": risk_action,
            "trust_score": trust_score,
            "ontology_valid": ontology_valid,
        })

    def policy_ledger(self):
        """Return the full hash-chained gating decision log."""
        return self._post("/policy/ledger", {
        })

    def policy_verify_chain(self):
        """Re-derive every logged decision's hash and confirm chain linkage (tamper detection)."""
        return self._post("/policy/verify_chain", {
        })



    def reasoning_assert(self, subject, predicate, object):
        """Assert one ground fact (subject, predicate, object) into the knowledge base."""
        return self._post("/reasoning/assert", {
            "subject": subject,
            "predicate": predicate,
            "object": object,
        })

    def reasoning_infer(self):
        """Run forward-chaining inference to a fixpoint against the built-in rule set; returns the number of newly derived facts."""
        return self._post("/reasoning/infer", {
        })

    def reasoning_query(self, subject, predicate, object):
        """Query facts matching a pattern; use a leading '?' on subject/predicate/object to match any value (e.g. '?x')."""
        return self._post("/reasoning/query", {
            "subject": subject,
            "predicate": predicate,
            "object": object,
        })

    def reasoning_explain(self, subject, predicate, object):
        """Return the derivation trace (which rule fired, over which premises) for a derived fact."""
        return self._post("/reasoning/explain", {
            "subject": subject,
            "predicate": predicate,
            "object": object,
        })



    def replay_contradiction(self, subject, records_json):
        """Independently recompute a contradiction-arbitration claim from raw evidence records (JSON array, must include one contradiction.ArbitrationParams record)."""
        return self._post("/replay/contradiction", {
            "subject": subject,
            "records_json": records_json,
        })

    def replay_fusion(self, subject, records_json):
        """Independently recompute a fusion-arbitration result from raw evidence records (JSON array, must include one fusion arbitration-params record)."""
        return self._post("/replay/fusion", {
            "subject": subject,
            "records_json": records_json,
        })



    def trust_evaluate(self, subject_id, win_rate, contradiction_rate, tick):
        """Compute a trust score for a subject from win_rate/contradiction_rate evidence, without issuing a certificate."""
        return self._post("/trust/evaluate", {
            "subject_id": subject_id,
            "win_rate": win_rate,
            "contradiction_rate": contradiction_rate,
            "tick": tick,
        })

    def trust_certify(self, subject_id, win_rate, contradiction_rate, tick):
        """Evaluate, and issue a hash-chained TrustCertificate if the score clears the policy threshold."""
        return self._post("/trust/certify", {
            "subject_id": subject_id,
            "win_rate": win_rate,
            "contradiction_rate": contradiction_rate,
            "tick": tick,
        })

    def trust_ledger(self):
        """Return the full hash-chained certificate history."""
        return self._post("/trust/ledger", {
        })

    def trust_verify_ledger(self):
        """Re-derive every certificate's hash and confirm chain linkage (tamper detection)."""
        return self._post("/trust/verify_ledger", {
        })



    def verification_verify(self, domain, subject, records_json, claimed_result):
        """records_json is a JSON array of {\"Kind\":..,\"Index\":..,\"Payload\":<base64>}; domain selects the independent replay function (\"contradiction\" or \"fusion\")."""
        return self._post("/verification/verify", {
            "domain": domain,
            "subject": subject,
            "records_json": records_json,
            "claimed_result": claimed_result,
        })

    def verification_verify_certificate(self, certificate_json):
        """Given a previously-issued AuditCertificate as JSON, confirm (third-party, bundle-free) that it has not been altered."""
        return self._post("/verification/verify_certificate", {
            "certificate_json": certificate_json,
        })


