// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
//
// Client is the generated Go SDK: a typed wrapper per contract method.
// This session's honest scope: the SDK calls the Engine Registry
// in-process (Go function calls) rather than over a network transport
// — Contract -> Serialize -> Transport -> Return with a real
// network/gRPC transport is the explicitly-named next step, not
// fabricated here. What IS real: every method below is generated
// mechanically from the same contract the CLI is generated from, and
// calls straight through to the same tested registry.Registry used by
// the CLI and gateway, so all three surfaces are provably consistent
// with each other by construction.
package sdk

import (
	"veriqo/pkg/evidence/graph"
	"veriqo/pkg/kernel/intent"
	"veriqo/pkg/kernel/policy"
	"veriqo/pkg/kernel/reasoning"
	"veriqo/pkg/trust"
	"veriqo/veriqo/registry"
)

// Client wraps a Registry with typed, contract-generated methods.
type Client struct {
	reg *registry.Registry
}

// NewClient builds an SDK client around a real Registry (which in turn
// wraps the real, tested pkg/trust and pkg/kernel/intent engines).
func NewClient(reg *registry.Registry) *Client { return &Client{reg: reg} }

// Register (or dedupe onto) a content-addressed evidence node and return its NodeID.
func (c *Client) EvidenceAddNode(kind string, payload string) (string, error) {
	return c.reg.Evidence.AddNode(kind, payload)
}

// Record a provenance relationship between two existing nodes (relation: derived_from|supports|contradicts|corrects).
func (c *Client) EvidenceAddEdge(from string, to string, relation string) (string, error) {
	return c.reg.Evidence.AddEdge(from, to, relation)
}

// Return the full ancestry of a node — everything it was derived from or corrected by, breadth-first.
func (c *Client) EvidenceLineage(id string) ([]graph.Node, error) {
	return c.reg.Evidence.Lineage(id)
}

// Return everything a node influenced forward — the exact inverse traversal of lineage.
func (c *Client) EvidenceInfluenced(id string) ([]graph.Node, error) {
	return c.reg.Evidence.Influenced(id)
}

// Return the current node/edge counts.
func (c *Client) EvidenceStats() (string, error) {
	return c.reg.Evidence.Stats()
}

// Compare a declared intent's expected outcome to what was actually observed and compute the trust delta, without issuing a certificate.
func (c *Client) IntentVerify(intent_id string, subject string, expected_action string, observed_action string, expected_risk float64, observed_risk float64, tick uint64) (intent.Verdict, error) {
	return c.reg.Intent.Verify(intent_id, subject, expected_action, observed_action, expected_risk, observed_risk, tick)
}

// Verify, and issue a hash-chained trust certificate if the subject's running accuracy clears its policy threshold.
func (c *Client) IntentCertify(intent_id string, subject string, expected_action string, observed_action string, expected_risk float64, observed_risk float64, tick uint64) (intent.Verdict, error) {
	return c.reg.Intent.Certify(intent_id, subject, expected_action, observed_action, expected_risk, observed_risk, tick)
}

// Return the full hash-chained trust certificate history for this Verifier.
func (c *Client) IntentLedger() ([]trust.TrustCertificate, error) {
	return c.reg.Intent.Ledger()
}

// Gate one action; ontology_valid is \"true\"/\"false\". Returns ALLOW, DENY, or REQUIRE_APPROVAL.
func (c *Client) PolicyEvaluate(action string, subject string, risk_action string, trust_score float64, ontology_valid string) (string, error) {
	return c.reg.Policy.Evaluate(action, subject, risk_action, trust_score, ontology_valid)
}

// Return the full hash-chained gating decision log.
func (c *Client) PolicyLedger() ([]policy.Record, error) {
	return c.reg.Policy.Ledger()
}

// Re-derive every logged decision's hash and confirm chain linkage (tamper detection).
func (c *Client) PolicyVerifyChain() (string, error) {
	return c.reg.Policy.VerifyChain()
}

// Assert one ground fact (subject, predicate, object) into the knowledge base.
func (c *Client) ReasoningAssert(subject string, predicate string, object string) (string, error) {
	return c.reg.Reasoning.Assert(subject, predicate, object)
}

// Run forward-chaining inference to a fixpoint against the built-in rule set; returns the number of newly derived facts.
func (c *Client) ReasoningInfer() (uint64, error) {
	return c.reg.Reasoning.Infer()
}

// Query facts matching a pattern; use a leading '?' on subject/predicate/object to match any value (e.g. '?x').
func (c *Client) ReasoningQuery(subject string, predicate string, object string) ([]reasoning.Triple, error) {
	return c.reg.Reasoning.Query(subject, predicate, object)
}

// Return the derivation trace (which rule fired, over which premises) for a derived fact.
func (c *Client) ReasoningExplain(subject string, predicate string, object string) (reasoning.Derivation, error) {
	return c.reg.Reasoning.Explain(subject, predicate, object)
}

// Independently recompute a contradiction-arbitration claim from raw evidence records (JSON array, must include one contradiction.ArbitrationParams record).
func (c *Client) ReplayContradiction(subject string, records_json string) (string, error) {
	return c.reg.Replay.Contradiction(subject, records_json)
}

// Independently recompute a fusion-arbitration result from raw evidence records (JSON array, must include one fusion arbitration-params record).
func (c *Client) ReplayFusion(subject string, records_json string) (string, error) {
	return c.reg.Replay.Fusion(subject, records_json)
}

// Compute a trust score for a subject from win_rate/contradiction_rate evidence, without issuing a certificate.
func (c *Client) TrustEvaluate(subject_id string, win_rate float64, contradiction_rate float64, tick uint64) (trust.TrustScore, error) {
	return c.reg.Trust.Evaluate(subject_id, win_rate, contradiction_rate, tick)
}

// Evaluate, and issue a hash-chained TrustCertificate if the score clears the policy threshold.
func (c *Client) TrustCertify(subject_id string, win_rate float64, contradiction_rate float64, tick uint64) (trust.TrustScore, error) {
	return c.reg.Trust.Certify(subject_id, win_rate, contradiction_rate, tick)
}

// Return the full hash-chained certificate history.
func (c *Client) TrustLedger() ([]trust.TrustCertificate, error) {
	return c.reg.Trust.Ledger()
}

// Re-derive every certificate's hash and confirm chain linkage (tamper detection).
func (c *Client) TrustVerifyLedger() (string, error) {
	return c.reg.Trust.VerifyLedger()
}

// records_json is a JSON array of {\"Kind\":..,\"Index\":..,\"Payload\":<base64>}; domain selects the independent replay function (\"contradiction\" or \"fusion\").
func (c *Client) VerificationVerify(domain string, subject string, records_json string, claimed_result string) (string, error) {
	return c.reg.Verification.Verify(domain, subject, records_json, claimed_result)
}

// Given a previously-issued AuditCertificate as JSON, confirm (third-party, bundle-free) that it has not been altered.
func (c *Client) VerificationVerifyCertificate(certificate_json string) (string, error) {
	return c.reg.Verification.VerifyCertificate(certificate_json)
}
