// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"veriqo/veriqo/registry"
)

// commandTable maps "engine method" to its handler, built from the
// contract files at generation time — the CLI never hand-maintains
// this list.
var commandTable = map[string]func(reg *registry.Registry, args []string) error{
	"evidence add_node":               cmdEvidenceAddNode,
	"evidence add_edge":               cmdEvidenceAddEdge,
	"evidence lineage":                cmdEvidenceLineage,
	"evidence influenced":             cmdEvidenceInfluenced,
	"evidence stats":                  cmdEvidenceStats,
	"intent verify":                   cmdIntentVerify,
	"intent certify":                  cmdIntentCertify,
	"intent ledger":                   cmdIntentLedger,
	"policy evaluate":                 cmdPolicyEvaluate,
	"policy ledger":                   cmdPolicyLedger,
	"policy verify_chain":             cmdPolicyVerifyChain,
	"reasoning assert":                cmdReasoningAssert,
	"reasoning infer":                 cmdReasoningInfer,
	"reasoning query":                 cmdReasoningQuery,
	"reasoning explain":               cmdReasoningExplain,
	"replay contradiction":            cmdReplayContradiction,
	"replay fusion":                   cmdReplayFusion,
	"trust evaluate":                  cmdTrustEvaluate,
	"trust certify":                   cmdTrustCertify,
	"trust ledger":                    cmdTrustLedger,
	"trust verify_ledger":             cmdTrustVerifyLedger,
	"verification verify":             cmdVerificationVerify,
	"verification verify_certificate": cmdVerificationVerifyCertificate,
}

// Register (or dedupe onto) a content-addressed evidence node and return its NodeID.
func cmdEvidenceAddNode(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("evidence add_node", flag.ExitOnError)
	kind := fs.String("kind", "", "kind (string)")
	payload := fs.String("payload", "", "payload (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Evidence.AddNode(*kind, *payload)
	if err != nil {
		return fmt.Errorf("evidence add_node: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Record a provenance relationship between two existing nodes (relation: derived_from|supports|contradicts|corrects).
func cmdEvidenceAddEdge(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("evidence add_edge", flag.ExitOnError)
	from := fs.String("from", "", "from (string)")
	to := fs.String("to", "", "to (string)")
	relation := fs.String("relation", "", "relation (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Evidence.AddEdge(*from, *to, *relation)
	if err != nil {
		return fmt.Errorf("evidence add_edge: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return the full ancestry of a node — everything it was derived from or corrected by, breadth-first.
func cmdEvidenceLineage(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("evidence lineage", flag.ExitOnError)
	id := fs.String("id", "", "id (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Evidence.Lineage(*id)
	if err != nil {
		return fmt.Errorf("evidence lineage: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return everything a node influenced forward — the exact inverse traversal of lineage.
func cmdEvidenceInfluenced(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("evidence influenced", flag.ExitOnError)
	id := fs.String("id", "", "id (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Evidence.Influenced(*id)
	if err != nil {
		return fmt.Errorf("evidence influenced: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return the current node/edge counts.
func cmdEvidenceStats(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("evidence stats", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Evidence.Stats()
	if err != nil {
		return fmt.Errorf("evidence stats: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Compare a declared intent's expected outcome to what was actually observed and compute the trust delta, without issuing a certificate.
func cmdIntentVerify(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("intent verify", flag.ExitOnError)
	intent_id := fs.String("intent_id", "", "intent_id (string)")
	subject := fs.String("subject", "", "subject (string)")
	expected_action := fs.String("expected_action", "", "expected_action (string)")
	observed_action := fs.String("observed_action", "", "observed_action (string)")
	expected_risk := fs.Float64("expected_risk", 0, "expected_risk (float)")
	observed_risk := fs.Float64("observed_risk", 0, "observed_risk (float)")
	tick := fs.Uint64("tick", 0, "tick (uint)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Intent.Verify(*intent_id, *subject, *expected_action, *observed_action, *expected_risk, *observed_risk, *tick)
	if err != nil {
		return fmt.Errorf("intent verify: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Verify, and issue a hash-chained trust certificate if the subject's running accuracy clears its policy threshold.
func cmdIntentCertify(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("intent certify", flag.ExitOnError)
	intent_id := fs.String("intent_id", "", "intent_id (string)")
	subject := fs.String("subject", "", "subject (string)")
	expected_action := fs.String("expected_action", "", "expected_action (string)")
	observed_action := fs.String("observed_action", "", "observed_action (string)")
	expected_risk := fs.Float64("expected_risk", 0, "expected_risk (float)")
	observed_risk := fs.Float64("observed_risk", 0, "observed_risk (float)")
	tick := fs.Uint64("tick", 0, "tick (uint)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Intent.Certify(*intent_id, *subject, *expected_action, *observed_action, *expected_risk, *observed_risk, *tick)
	if err != nil {
		return fmt.Errorf("intent certify: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return the full hash-chained trust certificate history for this Verifier.
func cmdIntentLedger(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("intent ledger", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Intent.Ledger()
	if err != nil {
		return fmt.Errorf("intent ledger: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Gate one action; ontology_valid is \"true\"/\"false\". Returns ALLOW, DENY, or REQUIRE_APPROVAL.
func cmdPolicyEvaluate(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("policy evaluate", flag.ExitOnError)
	action := fs.String("action", "", "action (string)")
	subject := fs.String("subject", "", "subject (string)")
	risk_action := fs.String("risk_action", "", "risk_action (string)")
	trust_score := fs.Float64("trust_score", 0, "trust_score (float)")
	ontology_valid := fs.String("ontology_valid", "", "ontology_valid (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Policy.Evaluate(*action, *subject, *risk_action, *trust_score, *ontology_valid)
	if err != nil {
		return fmt.Errorf("policy evaluate: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return the full hash-chained gating decision log.
func cmdPolicyLedger(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("policy ledger", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Policy.Ledger()
	if err != nil {
		return fmt.Errorf("policy ledger: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Re-derive every logged decision's hash and confirm chain linkage (tamper detection).
func cmdPolicyVerifyChain(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("policy verify_chain", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Policy.VerifyChain()
	if err != nil {
		return fmt.Errorf("policy verify_chain: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Assert one ground fact (subject, predicate, object) into the knowledge base.
func cmdReasoningAssert(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("reasoning assert", flag.ExitOnError)
	subject := fs.String("subject", "", "subject (string)")
	predicate := fs.String("predicate", "", "predicate (string)")
	object := fs.String("object", "", "object (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Reasoning.Assert(*subject, *predicate, *object)
	if err != nil {
		return fmt.Errorf("reasoning assert: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Run forward-chaining inference to a fixpoint against the built-in rule set; returns the number of newly derived facts.
func cmdReasoningInfer(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("reasoning infer", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Reasoning.Infer()
	if err != nil {
		return fmt.Errorf("reasoning infer: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Query facts matching a pattern; use a leading '?' on subject/predicate/object to match any value (e.g. '?x').
func cmdReasoningQuery(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("reasoning query", flag.ExitOnError)
	subject := fs.String("subject", "", "subject (string)")
	predicate := fs.String("predicate", "", "predicate (string)")
	object := fs.String("object", "", "object (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Reasoning.Query(*subject, *predicate, *object)
	if err != nil {
		return fmt.Errorf("reasoning query: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return the derivation trace (which rule fired, over which premises) for a derived fact.
func cmdReasoningExplain(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("reasoning explain", flag.ExitOnError)
	subject := fs.String("subject", "", "subject (string)")
	predicate := fs.String("predicate", "", "predicate (string)")
	object := fs.String("object", "", "object (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Reasoning.Explain(*subject, *predicate, *object)
	if err != nil {
		return fmt.Errorf("reasoning explain: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Independently recompute a contradiction-arbitration claim from raw evidence records (JSON array, must include one contradiction.ArbitrationParams record).
func cmdReplayContradiction(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("replay contradiction", flag.ExitOnError)
	subject := fs.String("subject", "", "subject (string)")
	records_json := fs.String("records_json", "", "records_json (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Replay.Contradiction(*subject, *records_json)
	if err != nil {
		return fmt.Errorf("replay contradiction: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Independently recompute a fusion-arbitration result from raw evidence records (JSON array, must include one fusion arbitration-params record).
func cmdReplayFusion(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("replay fusion", flag.ExitOnError)
	subject := fs.String("subject", "", "subject (string)")
	records_json := fs.String("records_json", "", "records_json (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Replay.Fusion(*subject, *records_json)
	if err != nil {
		return fmt.Errorf("replay fusion: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Compute a trust score for a subject from win_rate/contradiction_rate evidence, without issuing a certificate.
func cmdTrustEvaluate(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("trust evaluate", flag.ExitOnError)
	subject_id := fs.String("subject_id", "", "subject_id (string)")
	win_rate := fs.Float64("win_rate", 0, "win_rate (float)")
	contradiction_rate := fs.Float64("contradiction_rate", 0, "contradiction_rate (float)")
	tick := fs.Uint64("tick", 0, "tick (uint)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Trust.Evaluate(*subject_id, *win_rate, *contradiction_rate, *tick)
	if err != nil {
		return fmt.Errorf("trust evaluate: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Evaluate, and issue a hash-chained TrustCertificate if the score clears the policy threshold.
func cmdTrustCertify(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("trust certify", flag.ExitOnError)
	subject_id := fs.String("subject_id", "", "subject_id (string)")
	win_rate := fs.Float64("win_rate", 0, "win_rate (float)")
	contradiction_rate := fs.Float64("contradiction_rate", 0, "contradiction_rate (float)")
	tick := fs.Uint64("tick", 0, "tick (uint)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Trust.Certify(*subject_id, *win_rate, *contradiction_rate, *tick)
	if err != nil {
		return fmt.Errorf("trust certify: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Return the full hash-chained certificate history.
func cmdTrustLedger(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("trust ledger", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Trust.Ledger()
	if err != nil {
		return fmt.Errorf("trust ledger: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Re-derive every certificate's hash and confirm chain linkage (tamper detection).
func cmdTrustVerifyLedger(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("trust verify_ledger", flag.ExitOnError)
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Trust.VerifyLedger()
	if err != nil {
		return fmt.Errorf("trust verify_ledger: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// records_json is a JSON array of {\"Kind\":..,\"Index\":..,\"Payload\":<base64>}; domain selects the independent replay function (\"contradiction\" or \"fusion\").
func cmdVerificationVerify(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("verification verify", flag.ExitOnError)
	domain := fs.String("domain", "", "domain (string)")
	subject := fs.String("subject", "", "subject (string)")
	records_json := fs.String("records_json", "", "records_json (string)")
	claimed_result := fs.String("claimed_result", "", "claimed_result (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Verification.Verify(*domain, *subject, *records_json, *claimed_result)
	if err != nil {
		return fmt.Errorf("verification verify: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// Given a previously-issued AuditCertificate as JSON, confirm (third-party, bundle-free) that it has not been altered.
func cmdVerificationVerifyCertificate(reg *registry.Registry, args []string) error {
	fs := flag.NewFlagSet("verification verify_certificate", flag.ExitOnError)
	certificate_json := fs.String("certificate_json", "", "certificate_json (string)")
	if err := fs.Parse(args); err != nil {
		return err
	}
	result, err := reg.Verification.VerifyCertificate(*certificate_json)
	if err != nil {
		return fmt.Errorf("verification verify_certificate: %w", err)
	}
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}
