// Code generated by veriqo/generator from veriqo/contracts/*.yaml. DO NOT EDIT.
// Regenerate with: go run ./veriqo/generator/cmd/gen
//
// VeriqoClient is the generated TypeScript SDK: a thin, dependency-
// free (fetch only) HTTP client per contract method, calling the
// veriqo/gateway/rest gateway that fronts the same Engine Registry the
// Go CLI/SDK and Python SDK call.

export class VeriqoError extends Error {}

export class VeriqoClient {
  private baseUrl: string;

  constructor(baseUrl: string = "http://127.0.0.1:8080") {
    this.baseUrl = baseUrl.replace(/\/$/, "");
  }

  private async post(path: string, payload: unknown): Promise<any> {
    const res = await fetch(this.baseUrl + path, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });
    if (!res.ok) {
      const body = await res.text();
      throw new VeriqoError("POST " + path + " failed: " + res.status + " " + body);
    }
    return res.json();
  }


  /** Register (or dedupe onto) a content-addressed evidence node and return its NodeID. */
  async evidenceAddNode(kind: string, payload: string): Promise<any> {
    return this.post("/evidence/add_node", { kind, payload });
  }

  /** Record a provenance relationship between two existing nodes (relation: derived_from|supports|contradicts|corrects). */
  async evidenceAddEdge(from: string, to: string, relation: string): Promise<any> {
    return this.post("/evidence/add_edge", { from, to, relation });
  }

  /** Return the full ancestry of a node — everything it was derived from or corrected by, breadth-first. */
  async evidenceLineage(id: string): Promise<any> {
    return this.post("/evidence/lineage", { id });
  }

  /** Return everything a node influenced forward — the exact inverse traversal of lineage. */
  async evidenceInfluenced(id: string): Promise<any> {
    return this.post("/evidence/influenced", { id });
  }

  /** Return the current node/edge counts. */
  async evidenceStats(): Promise<any> {
    return this.post("/evidence/stats", {  });
  }



  /** Compare a declared intent's expected outcome to what was actually observed and compute the trust delta, without issuing a certificate. */
  async intentVerify(intent_id: string, subject: string, expected_action: string, observed_action: string, expected_risk: number, observed_risk: number, tick: number): Promise<any> {
    return this.post("/intent/verify", { intent_id, subject, expected_action, observed_action, expected_risk, observed_risk, tick });
  }

  /** Verify, and issue a hash-chained trust certificate if the subject's running accuracy clears its policy threshold. */
  async intentCertify(intent_id: string, subject: string, expected_action: string, observed_action: string, expected_risk: number, observed_risk: number, tick: number): Promise<any> {
    return this.post("/intent/certify", { intent_id, subject, expected_action, observed_action, expected_risk, observed_risk, tick });
  }

  /** Return the full hash-chained trust certificate history for this Verifier. */
  async intentLedger(): Promise<any> {
    return this.post("/intent/ledger", {  });
  }



  /** Gate one action; ontology_valid is \"true\"/\"false\". Returns ALLOW, DENY, or REQUIRE_APPROVAL. */
  async policyEvaluate(action: string, subject: string, risk_action: string, trust_score: number, ontology_valid: string): Promise<any> {
    return this.post("/policy/evaluate", { action, subject, risk_action, trust_score, ontology_valid });
  }

  /** Return the full hash-chained gating decision log. */
  async policyLedger(): Promise<any> {
    return this.post("/policy/ledger", {  });
  }

  /** Re-derive every logged decision's hash and confirm chain linkage (tamper detection). */
  async policyVerifyChain(): Promise<any> {
    return this.post("/policy/verify_chain", {  });
  }



  /** Assert one ground fact (subject, predicate, object) into the knowledge base. */
  async reasoningAssert(subject: string, predicate: string, object: string): Promise<any> {
    return this.post("/reasoning/assert", { subject, predicate, object });
  }

  /** Run forward-chaining inference to a fixpoint against the built-in rule set; returns the number of newly derived facts. */
  async reasoningInfer(): Promise<any> {
    return this.post("/reasoning/infer", {  });
  }

  /** Query facts matching a pattern; use a leading '?' on subject/predicate/object to match any value (e.g. '?x'). */
  async reasoningQuery(subject: string, predicate: string, object: string): Promise<any> {
    return this.post("/reasoning/query", { subject, predicate, object });
  }

  /** Return the derivation trace (which rule fired, over which premises) for a derived fact. */
  async reasoningExplain(subject: string, predicate: string, object: string): Promise<any> {
    return this.post("/reasoning/explain", { subject, predicate, object });
  }



  /** Independently recompute a contradiction-arbitration claim from raw evidence records (JSON array, must include one contradiction.ArbitrationParams record). */
  async replayContradiction(subject: string, records_json: string): Promise<any> {
    return this.post("/replay/contradiction", { subject, records_json });
  }

  /** Independently recompute a fusion-arbitration result from raw evidence records (JSON array, must include one fusion arbitration-params record). */
  async replayFusion(subject: string, records_json: string): Promise<any> {
    return this.post("/replay/fusion", { subject, records_json });
  }



  /** Compute a trust score for a subject from win_rate/contradiction_rate evidence, without issuing a certificate. */
  async trustEvaluate(subject_id: string, win_rate: number, contradiction_rate: number, tick: number): Promise<any> {
    return this.post("/trust/evaluate", { subject_id, win_rate, contradiction_rate, tick });
  }

  /** Evaluate, and issue a hash-chained TrustCertificate if the score clears the policy threshold. */
  async trustCertify(subject_id: string, win_rate: number, contradiction_rate: number, tick: number): Promise<any> {
    return this.post("/trust/certify", { subject_id, win_rate, contradiction_rate, tick });
  }

  /** Return the full hash-chained certificate history. */
  async trustLedger(): Promise<any> {
    return this.post("/trust/ledger", {  });
  }

  /** Re-derive every certificate's hash and confirm chain linkage (tamper detection). */
  async trustVerifyLedger(): Promise<any> {
    return this.post("/trust/verify_ledger", {  });
  }



  /** records_json is a JSON array of {\"Kind\":..,\"Index\":..,\"Payload\":<base64>}; domain selects the independent replay function (\"contradiction\" or \"fusion\"). */
  async verificationVerify(domain: string, subject: string, records_json: string, claimed_result: string): Promise<any> {
    return this.post("/verification/verify", { domain, subject, records_json, claimed_result });
  }

  /** Given a previously-issued AuditCertificate as JSON, confirm (third-party, bundle-free) that it has not been altered. */
  async verificationVerifyCertificate(certificate_json: string): Promise<any> {
    return this.post("/verification/verify_certificate", { certificate_json });
  }


}
